### ISSUE TITLE
About sound card sampling rate

### ISSUE THREAD

**Issue by Trendy73** [ke9ns/PowerSDR_KE9NS_v2.8.0#1]
Hello, Darrin
What is the maximum sampling rate that this Power SDR v2.8.0 can support?
73

**Comment by ke9ns** [comment]
My version of PowerSDR max is 192khz
Thats really defined by the capability of the FlexRadio legacy Radios, and the capability of the 1394A connection between the PC and the Radio


Darrinke9ns.com


    On Saturday, July 20, 2024 at 05:46:09 AM CDT, Trendy ***@***.***> wrote:  
 
 


Hello, Darrin
What is the maximum sampling rate that this Power SDR v2.8.0 can support?
73

**Comment by Trendyfu** [comment]
Thanks for the reply.
Does this mean that even if my SDR and sound card support 384Khz sampling rate, I can still only use up to 192khz?
73

**Comment by Trendy73** [comment]
> My version of PowerSDR max is 192khz Thats really defined by the capability of the FlexRadio legacy Radios, and the capability of the 1394A connection between the PC and the Radio Darrinke9ns.com On Saturday, July 20, 2024 at 05:46:09 AM CDT, Trendy ***@***.***> wrote: Hello, Darrin What is the maximum sampling rate that this Power SDR v2.8.0 can support? 73 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Thanks for the reply.
Does this mean that even if my SDR and sound card support 384Khz sampling rate, I can still only use up to 192khz?
73

**Comment by ke9ns** [comment]
I think in order for my software to work with an SDR other than the 1500,3000,5000 legacy radios (which dont use the sound card), you would need use the older version of PowerSDR (for the SDR-1000) that was designed to directly sample the I.F. using an audio card input. There is this link: https://github.com/US1GHQ/PowerSDR-2.8.0-SDR-1000but this person stopped porting over my code at .239 (I think due to the Ukrainian war). His version works with many other SDRs that use the sound card for the I.F.

But you could definitely modify the code to allow a higher SR if your sound card can handle itThen you would need to modify the Panadapter and Waterfall to also allow for a larger possible I.F. width
73
Darrinke9ns.com




    On Sunday, July 21, 2024 at 01:06:14 AM CDT, Trendy ***@***.***> wrote:  
 
 



My version of PowerSDR max is 192khz Thats really defined by the capability of the FlexRadio legacy Radios, and the capability of the 1394A connection between the PC and the Radio Darrinke9ns.com On Saturday, July 20, 2024 at 05:46:09 AM CDT, Trendy @.> wrote: Hello, Darrin What is the maximum sampling rate that this Power SDR v2.8.0 can support? 73 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>


Thanks for the reply.
Does this mean that even if my SDR and sound card support 384Khz sampling rate, I can still only use up to 192khz?
73

**Comment by Trendy73** [comment]
> I think in order for my software to work with an SDR other than the 1500,3000,5000 legacy radios (which dont use the sound card), you would need use the older version of PowerSDR (for the SDR-1000) that was designed to directly sample the I.F. using an audio card input. There is this link: https://github.com/US1GHQ/PowerSDR-2.8.0-SDR-1000but this person stopped porting over my code at .239 (I think due to the Ukrainian war). His version works with many other SDRs that use the sound card for the I.F. But you could definitely modify the code to allow a higher SR if your sound card can handle itThen you would need to modify the Panadapter and Waterfall to also allow for a larger possible I.F. width 73 Darrinke9ns.com On Sunday, July 21, 2024 at 01:06:14 AM CDT, Trendy ***@***.***> wrote: My version of PowerSDR max is 192khz Thats really defined by the capability of the FlexRadio legacy Radios, and the capability of the 1394A connection between the PC and the Radio Darrinke9ns.com On Saturday, July 20, 2024 at 05:46:09 AM CDT, Trendy @.> wrote: Hello, Darrin What is the maximum sampling rate that this Power SDR v2.8.0 can support? 73 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> Thanks for the reply. Does this mean that even if my SDR and sound card support 384Khz sampling rate, I can still only use up to 192khz? 73 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

I think I understand exactly what you are saying.
Thanks for your reply, I plan to use a variant of the SDR-1000, so you are right.
Unfortunately I am not good at modifying the code, so I can only use the current version.
73
